[package]
name = "ping-rs"
version = "0.0.0"
edition = "2021"

[dependencies]
socket2 = { version = "0.4", features = ["all"] }
pnet_packet = "0.31"
rand = "0.8"

[dev-dependencies]
more-asserts = "0.3"
