name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  clippy:
    name: Lint with cargo clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings # elevate warnings to errors
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        # key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.toml') }}
    - run: cargo clippy --workspace --all-targets --verbose --no-default-features
    - run: cargo clippy --workspace --all-targets --verbose --all-features

  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        # key: ${{ runner.os }}-cargo-build-and-test-${{ hashFiles('**/Cargo.lock') }}
        key: ${{ runner.os }}-cargo-build-and-test-${{ hashFiles('**/Cargo.toml') }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --lib --verbose
